services:
  ivr:
    image: ragsterisk:20
    networks:
      backend:        
        aliases:
          - ivr
      frontend:
        ipv4_address: ${IP_VOIP}
    ports:
      - "5060:5060/udp"
      - "10000-10099:10000-10099/udp"
    environment:
      SYSLOG_LEVEL: ${SYSLOG_LEVEL-4}      # Logging
      HOSTNAME: ${TELE_SRV-tele}.${DOMAIN-docker.localhost}
      PULSE_SERVER: unix:/run/pulse/socket # Use host audio
      PULSE_COOKIE: /run/pulse/cookie      # Use host audio
      WEBSMSD_PORT: ${WEBSMSD_PORT-80}     # WEBSMSD internal port
    volumes:
      #- ./srv:/srv                      # Persistent storage
      #- ./pulse:/run/pulse:rshared          # Use host audio
      - /etc/localtime:/etc/localtime:ro    # Use host timezone
      - ./CAcert.crt:/tmp/CAcert.crt
      - ./fixssl:/usr/bin/fixssl
      - ./ragsterisk/app/sound:/var/lib/asterisk/sounds/custom
      - ./ragsterisk/app/sound:/opt/agi/app/sound
      - ./ragsterisk/config/:/etc/asterisk
      - ./ragsterisk/app/rag_agi.py:/var/lib/asterisk/agi-bin/app/rag_agi.py
  ragapi:
    image: ragapi:1.01
    volumes:
      - ./CAcert.crt:/tmp/CAcert.crt
      - ./ragapi/app/:/opt/rag/app/
      - ./ragapi/startup.sh/:/usr/local/bin/startup.sh
    env_file:
      - .env
    networks:
      backend:
        aliases:
          - ragapi
      frontend:
        ipv4_address: ${IP_FRONT}
    ports:
      - 8000:8000
  ollama:
    image: ollama/ollama
    volumes:
      - ./ragapi/data:/root/.ollama
    networks:
      frontend:
      backend:
        aliases:
          - ollama
    ports:
      - 11434:11434

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    volumes:
     - ./redis-data:/var/lib/redis
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      backend:
        aliases:
          - redis

networks:
  frontend:
    name: ${NETWORK}
    external: true
  backend:
    internal: true
