;-------------------------------- PrivateDial ----------------------------------
; Filename: pjsip.conf
; This file is an Asterisk configuration file, part of the PrivateDial suite.
; It is loaded by the chan_pjsip.so module.
;

;-------------------------------- global ---------------------------------------

[global]
type = global
user_agent = Platform PBX

;-------------------------------- includes -------------------------------------

#tryinclude pjsip_transport.conf

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

; Ext 1001

[1001]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw
auth=1001
aors=1001

[1001]
type=auth
auth_type=userpass
password=1001
username=1001

[1001]
type=aor
max_contacts=1

; Ext 1002

[1002]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw
auth=1002
aors=1002

[1002]
type=auth
auth_type=userpass
password=1002
username=1002

[1002]
type=aor
max_contacts=1
