; Ext 1001
[from-internal]
exten => 1001,1,NoOp(Inicio de llamada automatica 1001)
 same => n,Set(CHANNEL(language)=en) 
exten => 1001,n,Answer()
exten => 1001,n,Dial(PJSIP/1001)
exten => 1001,n,Hangup()

; Ext 1002
exten => 1002,1,NoOp(Inicio de llamada automatica 1002)
 same => n,Set(CHANNEL(language)=en) 
exten => 1002,n,Answer()
exten => 1002,n,Dial(PJSIP/1002)
exten => 1002,n,Hangup()

; Ext 1003
exten => 1003,1,NoOp(Inicio de llamada automatica 1003)
 same => n,Set(CHANNEL(language)=en)
 same => n,Answer()
 same => n,Dial(PJSIP/1003)
 same => n,Hangup()

exten => 1234,1,NoOp(Llamada a ChatGPT AGI)
 same => n,Set(CHANNEL(language)=en) 
 same => n,Answer()
 same => n,Wait(1)
 same => n,AGI(app/rag_agi.py)
 same => n,ExecIf($["${AGISTATUS}" != "SUCCESS"]?Hangup())
 same => n,Hangup()


exten => 1236,1,Answer()
 same => n,Set(CHANNEL(language)=en)
 same => n,Playback(hello-world)
 same => n,Hangup()
