[transport-udp]
type=transport
protocol=udp
domain=pbx.local
bind=0.0.0.0
local_net=10.66.20.0/24  ; Red de los clientes
local_net=192.168.2.0/24  ; Otra red de los clientes
external_media_address=172.17.110.178  ; IP publica del servidor
external_signaling_address=172.17.110.178  ; IP publica del servidor

[1001]
type = wizard
accepts_auth = yes
accepts_registrations = yes
endpoint/context = from-internal
endpoint/allow = ulaw
inbound_auth/username = 1001
inbound_auth/password = 1001
aor/max_contacts = 10

[1002]
type = wizard
accepts_auth = yes
accepts_registrations = yes
endpoint/context = from-internal
endpoint/allow = ulaw
inbound_auth/username = 1002
inbound_auth/password = 1002
aor/max_contacts = 10

[1003]
type = wizard
accepts_auth = yes
accepts_registrations = yes
endpoint/context = from-internal
endpoint/allow = ulaw
inbound_auth/username = 1003
inbound_auth/password = 1003
aor/max_contacts = 10
